import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import styles from './ScheduleHistory.module.css';
import {
  LuCalendar,
  LuClock,
  LuMapPin,
  LuMessageCircle,
  LuFileText,
  LuChevronDown,
  LuPause,
  LuRotateCcw,
  LuMonitor,
  LuWifi,
  LuTriangleAlert,
  LuCircleCheck,
  LuCircleX,
} from 'react-icons/lu';
import { FaHome, FaUsers } from 'react-icons/fa';

const dummyScheduleInstances = [
  {
    _id: 'instance1',
    scheduleId: 'sched001',
    classDate: '2025-08-01T09:00:00.000Z',
    classStatus: 'held',
    updatedTime: {
      start: '10:00',
      end: '12:00',
    },
    updatedLocation: 'LT1, Science Complex',
    deliveryMode: 'physical',
    isAutoGenerated: false,
    lecturerMessage: "Please revise last week's material before class.",
    feedbackFromLecturer: 'Great student interaction today.',
    syllabusTopic: 'Introduction to Enzyme Kinetics',
    notes: 'Covered Michaelis-Menten equation and Lineweaver-Burk plot.',
    createdBy: 'rep123',
    createdByName: 'Felix Vincent',
    attendanceSummary: {
      totalPresent: 18,
      totalAbsent: 2,
      totalLate: 3,
    },
    studentPresence: [
      { studentId: 'stu1', status: 'present' },
      { studentId: 'stu2', status: 'late' },
      { studentId: 'stu3', status: 'absent' },
    ],
  },
  {
    _id: 'instance2',
    scheduleId: 'sched002',
    classDate: '2025-08-03T09:00:00.000Z',
    classStatus: 'cancelled',
    deliveryMode: 'physical',
    isAutoGenerated: true,
    lecturerMessage: 'Class cancelled due to unforeseen circumstances.',
    feedbackFromLecturer: '',
    syllabusTopic: '',
    notes: '',
    createdBy: 'admin001',
    createdByName: 'Admin Manager',
    attendanceSummary: {
      totalPresent: 0,
      totalAbsent: 0,
      totalLate: 0,
    },
    studentPresence: [],
  },
  {
    _id: 'instance3',
    scheduleId: 'sched003',
    classDate: '2025-08-05T14:00:00.000Z',
    classStatus: 'postponed',
    rescheduledToDate: '2025-08-08T14:00:00.000Z',
    deliveryMode: 'virtual',
    isAutoGenerated: false,
    lecturerMessage: 'Class postponed due to public holiday.',
    feedbackFromLecturer: '',
    syllabusTopic: 'Bioenergetics',
    notes: '',
    createdBy: 'rep456',
    createdByName: 'Muna James',
    attendanceSummary: {
      totalPresent: 0,
      totalAbsent: 0,
      totalLate: 0,
    },
    studentPresence: [],
  },
  {
    _id: 'instance4',
    scheduleId: 'sched004',
    classDate: '2025-08-06T08:00:00.000Z',
    classStatus: 'rescheduled',
    rescheduledToDate: '2025-08-06T15:00:00.000Z',
    updatedTime: {
      start: '15:00',
      end: '17:00',
    },
    updatedLocation: 'LT2, Engineering Hall',
    deliveryMode: 'hybrid',
    isAutoGenerated: false,
    lecturerMessage: 'Class time changed due to department meeting.',
    feedbackFromLecturer: 'Low participation online.',
    syllabusTopic: 'Thermodynamics in Biochemistry',
    notes: 'Focused on entropy and Gibbs free energy.',
    createdBy: 'rep789',
    createdByName: 'Samuel Obi',
    attendanceSummary: {
      totalPresent: 12,
      totalAbsent: 6,
      totalLate: 1,
    },
    studentPresence: [
      { studentId: 'stuA', status: 'present' },
      { studentId: 'stuB', status: 'present' },
      { studentId: 'stuC', status: 'late' },
    ],
  },
  {
    _id: 'instance5',
    scheduleId: 'sched005',
    classDate: '2025-08-07T08:00:00.000Z',
    classStatus: 'missed',
    deliveryMode: 'physical',
    isAutoGenerated: true,
    lecturerMessage: '',
    feedbackFromLecturer: '',
    syllabusTopic: '',
    notes: '',
    createdBy: 'rep999',
    createdByName: 'Rita Nwachukwu',
    attendanceSummary: {
      totalPresent: 0,
      totalAbsent: 0,
      totalLate: 0,
    },
    studentPresence: [],
  },
];

const ScheduleHistory = () => {
  const [expandedCard, setExpandedCard] = useState(null);

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return {
      day: date.getDate(),
      month: date.toLocaleDateString('en-US', { month: 'short' }),
      weekday: date.toLocaleDateString('en-US', { weekday: 'long' }),
      time: date.toLocaleTimeString('en-US', {
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
      }),
    };
  };

  const getStatusConfig = (status) => {
    const configs = {
      held: {
        color: '#10b981',
        bgColor: '#ecfdf5',
        icon: LuCircleCheck,
        text: 'Completed',
      },
      cancelled: {
        color: '#ef4444',
        bgColor: '#fef2f2',
        icon: LuCircleX,
        text: 'Cancelled',
      },
      postponed: {
        color: '#f59e0b',
        bgColor: '#fffbeb',
        icon: LuPause,
        text: 'Postponed',
      },
      rescheduled: {
        color: '#3b82f6',
        bgColor: '#eff6ff',
        icon: LuRotateCcw,
        text: 'Rescheduled',
      },
      missed: {
        color: '#ef4444',
        bgColor: '#fef2f2',
        icon: LuTriangleAlert,
        text: 'Missed',
      },
    };
    return configs[status] || configs.held;
  };

  const getDeliveryModeIcon = (mode) => {
    switch (mode) {
      case 'virtual':
        return LuMonitor;
      case 'hybrid':
        return LuWifi;
      case 'physical':
      default:
        return FaHome;
    }
  };

  const toggleExpanded = (instanceId) => {
    setExpandedCard(expandedCard === instanceId ? null : instanceId);
  };

  const cardVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.3 },
    },
    hover: {
      y: -2,
      boxShadow: '0 10px 25px rgba(59, 130, 246, 0.15)',
      transition: { duration: 0.2 },
    },
  };

  const expandVariants = {
    collapsed: { height: 0, opacity: 0 },
    expanded: {
      height: 'auto',
      opacity: 1,
      transition: { duration: 0.3, ease: 'easeInOut' },
    },
  };

  return (
    <div className={styles.wrapper}>
      <div className={styles.container}>
        {/* Header */}
        <motion.div
          className={styles.sectionHeader}
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}>
          <div className={styles.headerContent}>
            <h1 className={styles.title}>📅 Class Schedule History</h1>
            <p className={styles.subtitle}>
              Stay organized — view, track, and manage all your upcoming and
              past class sessions.
            </p>
          </div>
        </motion.div>

        {/* Calendar Grid */}
        <div className={styles.cardsGrid}>
          {dummyScheduleInstances.map((instance, index) => {
            const dateInfo = formatDate(instance.classDate);
            const statusConfig = getStatusConfig(instance.classStatus);
            const StatusIcon = statusConfig.icon;
            const DeliveryIcon = getDeliveryModeIcon(instance.deliveryMode);
            const isExpanded = expandedCard === instance._id;

            return (
              <motion.div
                key={instance._id}
                variants={cardVariants}
                initial="hidden"
                animate="visible"
                whileHover="hover"
                transition={{ delay: index * 0.1 }}
                className={styles.card}
                onClick={() => toggleExpanded(instance._id)}>
                {/* Card Header */}
                <div
                  className={styles.cardHeader}
                  style={{
                    background: `linear-gradient(135deg, ${statusConfig.color} 0%, ${statusConfig.color}dd 100%)`,
                  }}>
                  <div className={styles.cardHeaderTop}>
                    <div>
                      <div className={styles.cardHeaderDate}>
                        {dateInfo.day}
                      </div>
                      <div className={styles.cardHeaderMonth}>
                        {dateInfo.month}
                      </div>
                    </div>

                    <div className={styles.cardStatus}>
                      <StatusIcon size={14} />
                      {statusConfig.text}
                    </div>
                  </div>

                  <div className={styles.cardWeekday}>{dateInfo.weekday}</div>

                  <div className={styles.cardTime}>
                    <LuClock size={14} />
                    {instance.updatedTime
                      ? `${instance.updatedTime.start} - ${instance.updatedTime.end}`
                      : dateInfo.time}
                  </div>
                </div>

                {/* Card Content */}
                <div className={styles.cardBody}>
                  <div className={styles.cardTitleRow}>
                    <h3 className={styles.cardTitle}>
                      {instance.syllabusTopic || 'No topic specified'}
                    </h3>

                    <motion.div
                      animate={{ rotate: isExpanded ? 180 : 0 }}
                      transition={{ duration: 0.2 }}>
                      <LuChevronDown
                        size={20}
                        color="#64748b"
                      />
                    </motion.div>
                  </div>

                  {/* Quick Info */}
                  <div className={styles.quickInfo}>
                    <div className={styles.quickInfoItem}>
                      <DeliveryIcon size={16} />
                      {instance.deliveryMode}
                    </div>

                    {instance.updatedLocation && (
                      <div className={styles.quickInfoItem}>
                        <LuMapPin size={16} />
                        {instance.updatedLocation}
                      </div>
                    )}

                    {instance.attendanceSummary.totalPresent > 0 && (
                      <div className={styles.quickInfoItem}>
                        <FaUsers size={16} />
                        {instance.attendanceSummary.totalPresent} present
                      </div>
                    )}
                  </div>

                  {/* Lecturer Message Preview */}
                  {instance.lecturerMessage && (
                    <div className={styles.lecturerMessage}>
                      <p>
                        {instance.lecturerMessage.length > 80 && !isExpanded
                          ? `${instance.lecturerMessage.substring(0, 80)}...`
                          : instance.lecturerMessage}
                      </p>
                    </div>
                  )}

                  {/* Expanded Content */}
                  <AnimatePresence>
                    {isExpanded && (
                      <motion.div
                        variants={expandVariants}
                        initial="collapsed"
                        animate="expanded"
                        exit="collapsed"
                        style={{ overflow: 'hidden' }}>
                        <div className={styles.detailedInfo}>
                          {/* Detailed Info */}
                          <div className={styles.infoGrid}>
                            <div className={styles.infoBox}>
                              <div className={styles.infoBoxLabel}>
                                Created By
                              </div>
                              <div className={styles.infoBoxValue}>
                                {instance.createdByName}
                              </div>
                            </div>

                            <div className={styles.infoBox}>
                              <div className={styles.infoBoxLabel}>
                                Schedule ID
                              </div>
                              <div
                                className={`${styles.infoBoxValue} ${styles.monospace}`}>
                                {instance.scheduleId}
                              </div>
                            </div>
                          </div>

                          {/* Attendance Summary */}
                          {instance.attendanceSummary.totalPresent > 0 && (
                            <div className={styles.attendanceSummary}>
                              <div className={styles.attendanceSummaryHeader}>
                                <FaUsers
                                  size={18}
                                  color="#3b82f6"
                                />
                                <span>Attendance Summary</span>
                              </div>
                              <div className={styles.attendanceStats}>
                                <div className={styles.statItem}>
                                  <div className={styles.statPresent}>
                                    {instance.attendanceSummary.totalPresent}
                                  </div>
                                  <div className={styles.statLabel}>
                                    Present
                                  </div>
                                </div>
                                <div className={styles.statItem}>
                                  <div className={styles.statLate}>
                                    {instance.attendanceSummary.totalLate}
                                  </div>
                                  <div className={styles.statLabel}>Late</div>
                                </div>
                                <div className={styles.statItem}>
                                  <div className={styles.statAbsent}>
                                    {instance.attendanceSummary.totalAbsent}
                                  </div>
                                  <div className={styles.statLabel}>Absent</div>
                                </div>
                              </div>
                            </div>
                          )}

                          {/* Feedback */}
                          {instance.feedbackFromLecturer && (
                            <div className={styles.feedback}>
                              <div className={styles.feedbackHeader}>
                                <LuMessageCircle
                                  size={16}
                                  color="#10b981"
                                />
                                <span>Lecturer Feedback</span>
                              </div>
                              <p>{instance.feedbackFromLecturer}</p>
                            </div>
                          )}

                          {/* Notes */}
                          {instance.notes && (
                            <div className={styles.notes}>
                              <div className={styles.notesHeader}>
                                <LuFileText
                                  size={16}
                                  color="#f59e0b"
                                />
                                <span>Class Notes</span>
                              </div>
                              <p>{instance.notes}</p>
                            </div>
                          )}

                          {/* Reschedule Info */}
                          {instance.rescheduledToDate && (
                            <div className={styles.reschedule}>
                              <div className={styles.rescheduleHeader}>
                                <LuCalendar
                                  size={16}
                                  color="#3b82f6"
                                />
                                <span>Rescheduled To</span>
                              </div>
                              <p>
                                {formatDate(instance.rescheduledToDate).weekday}
                                , {formatDate(instance.rescheduledToDate).month}{' '}
                                {formatDate(instance.rescheduledToDate).day} at{' '}
                                {formatDate(instance.rescheduledToDate).time}
                              </p>
                            </div>
                          )}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default ScheduleHistory;
